package hello;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import hello.User;
import hello.UserRepository;

@Controller //This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController{
	
	private static final String REQUESTED = "requested";
	private static final String NEEDSTORESPOND = "needsToRespond";
	private static final String REJECTED = "rejectedBy";
	private static final String FRIENDS = "friends";
	private static final String NOTFRIENDS = "notFriends";
	
	@Autowired //This means to get the bean called userRepository
				// Which is auto-generated by Spring. We will use it to handle the data
	private UserRepository userRepository;
	
	@Autowired //This means to get the bean called userRepository
	// Which is auto-generated by Spring. We will use it to handle the data
	private UserRelationshipsRepository userRelationshipsRepository;

	
	@GetMapping(path="/enc")
	public @ResponseBody String enc(@RequestParam String payloadCipher, @RequestParam String encryptedKey) {
		String symmetricKey = decryptKey(encryptedKey);
		String[] msg = decryptMsg(payloadCipher, symmetricKey).split("\\?");
		String action = msg[0];
		String username = "";
		switch(action) {
			case "login":
				username = msg[1];
				String password = msg[2];
				return login(username, password, userRepository);
			case "add":
				username = msg[1];
				String passHash = msg[2];
				String userPublicKey = msg[3];
				String userPrivateKey = msg[4];
				return addNewUser(username, passHash, userPublicKey, userPrivateKey, userRepository);
				
			default: return "Server did not understand message.";
		}
	}
	
	public static String addNewUser(String username, String passHash, String userPublicKey, String encryptedUserPrivateKey, UserRepository userRepository){

		User u = userRepository.findByUsername(username);

		if(u != null) {
			return "User with that username already exists!";
		}

		User n = new User();
		n.setUsername(username);
		n.setPassHash(passHash);
		n.setUserPublicKey(userPublicKey);
		n.setEncryptedUserPrivateKey(encryptedUserPrivateKey);

		userRepository.save(n);
		return "Success";
	}
	
	public static String login(String username, String enteredPassword, UserRepository userRepository){
		User u = userRepository.findByUsername(username);
		if(u == null) {
			return "nologin";
		}
		
		String originalPassword = u.getPassHash();
		
		if(!Hasher.validatePassword(enteredPassword, originalPassword)) {
			return "wrong";
		}else {
			String resp = "";
			resp = resp + u.getUsername() + "?" + u.getEncryptedUserPrivateKey() + "?" + u.getUserPublicKey();
			return resp;
		}
	}
	
	private static String decryptKey(String encryptedKey) {
		String decryptedKey = RSACipher.decryptWithPrivate(ServerInfo.PRIVATEKEY, encryptedKey);
		return decryptedKey;
	}
	
	private static String decryptMsg(String payloadCipher, String symmetricKey) {
		return SymmetricCipher.decrypt(symmetricKey, payloadCipher, true);
	}
	
	@GetMapping(path="/addfriend")
	public @ResponseBody String addFriend(String from, String to, String type) {
		UserRelationships u = new UserRelationships();
		u.setFromUsername(from);
		u.setToUsername(to);
		u.setRelationshipType(type);
		
		UserRelationships u2 = new UserRelationships();
		u2.setFromUsername(to);
		u2.setToUsername(from);
		u2.setRelationshipType(type);
		//This returns a JSON or XML with the users
		userRelationshipsRepository.save(u);
		return "success";
	}
	
	@GetMapping(path="/getNumFriends")
	public @ResponseBody String getFriends(String from, String to) {
		List<UserRelationships> u = userRelationshipsRepository.findByFromUsername(from);

		return "" + u.size();
	}
	
	//tester
	@GetMapping(path="/requestFriend")
	public @ResponseBody String requestFriends(String from, String to) {
		return sendFriendRequest(from, to, userRelationshipsRepository, userRepository);
	}
	
	private static String sendFriendRequest(String fromUser, String toUser, UserRelationshipsRepository userRelationshipsRepository, UserRepository userRepository) {
		//check if the targetUser even exists
		User k = userRepository.findByUsername(toUser);
		if(k == null) {
			return "usernotexist";
		}
		
		//find a relationship between fromUser and toUser, if it exists
		UserRelationships existingRln = findRelationship(fromUser, toUser, userRelationshipsRepository);
		
		//if there was an existing relationship
		if(existingRln != null) {
			//are they already friends?
			if(existingRln.getRelationshipType().equals(FRIENDS)) {
				return "alreadyfriends";
			} 
			
			//have they already sent the target a request?
			if(existingRln.getRelationshipType().equals(REQUESTED) || existingRln.getRelationshipType().equals(REJECTED)) {
				return "alreadyrequested";
			}
			
			//else this user needsToRespond to a pending request from the target, or this user has previously rejected a request from the target
			existingRln.setRelationshipType(FRIENDS);
			
			//set the relationship type of the other persons to friends as well
			UserRelationships targetRln = findRelationship(toUser, fromUser, userRelationshipsRepository);
			targetRln.setRelationshipType(FRIENDS);
			
			userRelationshipsRepository.save(existingRln);
			userRelationshipsRepository.save(targetRln);
			return "becamefriends";
		}
		
		//There was not any existing relationship
		UserRelationships u = new UserRelationships();
		u.setFromUsername(fromUser);
		u.setToUsername(toUser);
		u.setRelationshipType(REQUESTED);
		
		UserRelationships u2 = new UserRelationships();
		u2.setFromUsername(toUser);
		u2.setToUsername(fromUser);
		u2.setRelationshipType(NEEDSTORESPOND);
		userRelationshipsRepository.save(u);
		userRelationshipsRepository.save(u2);
		return "sentrequest";
	}
	
	private static UserRelationships findRelationship(String source, String target, UserRelationshipsRepository userRelationshipsRepository) {
		//get list of all of source's relationships
		List<UserRelationships> u = userRelationshipsRepository.findByFromUsername(source);
		
		UserRelationships res = null;
		
		//check to see if the user had any relationships at all
		if(u != null && u.size() > 0) {
			//iterate through all of their relationships to see if there exists one with target
			for(int i = 0; i < u.size(); i++) {
				UserRelationships tmpRelationship = u.get(i);
				if(target.equals(tmpRelationship.getToUsername())) {
					res = tmpRelationship;
					break;
				}
			}
		}
		
		return res;
	}

	/*
	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		//This returns a JSON or XML with the users
		return userRepository.findAll();
	}
	
	@GetMapping(path="/get")
	public @ResponseBody String getByEmail(String username) {
		//This returns a JSON or XML with the users
		User u = userRepository.findByUsername(username);
		return u.getPassHash();
	}
	*/
}